### ISSUE TITLE
Test bountysource plugin [$5]

### ISSUE THREAD

**Issue by MichaelAtOz** [MichaelAtOz/Hello-World#3]
Does it work?

**Comment by vedant1811** [comment]
@MichaelAtOz I have mentioned that I am working on this issue. If you close this issue, then I will be eligible to claim the bounty

**Comment by MichaelAtOz** [comment]
@vedant1811 Sorry, this issues WAS the test. It worked.

**Comment by MichaelAtOz** [comment]
I am closing this to finalise the bountysource integration test.
