### ISSUE TITLE
Another test issue for Bountysource [$15]

### ISSUE THREAD

**Issue by MichaelAtOz** [MichaelAtOz/Hello-World#8]
Testing. This issue is for me to test bountysource functions. Not an actual bounty.

**Comment by isworking** [comment]
I found this issue on BountySource. Is it just for testing, or you're actually offering the money?

**Comment by MichaelAtOz** [comment]
It was both. I have fixed the BS problem, and I intended to leave the bounty, as a tide-bit for a handy feature that wasn't too complex.
So claim it.

**Comment by MichaelAtOz** [comment]
Sorry. I missed the issue you were asking about. I thought is was another topic.
No there is nothing here to do.. So no bounty.
